### ISSUE TITLE
wrong values in length/start via the buttons

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#13]
I set start and end points using one of the three available start and end buttons each.

Some start always gets set, but in my case it is a strange number: -1800176.031
Sometimes an end/length gets set to 0, sometimes to some (sensible) number.

The "common fixes" area gets preselected for submission. I click "ok" and get a:

"choice empty at /home/sreview/sreview/web/sreview line 51."

P.S. Checked this in the latest Firefox and Chrome on Debian testing.

It seems what always goes wrong is the two "pre"- and "post"-videos at the top.

**Comment by krokodilerian** [comment]
I get somewhat the same problem. Here's what I did:
I set a start and end for a talk, with the big video, then went to the one on the top left and set a start there. Then, in the length field I got "-18001062.946-2.61200000000008". Dunno if it's supposed to have an expression there, but -18001062 seems too big.

**Comment by markvdb** [comment]
Might be 1800 seconds (talk length) and a random other number gotten from the js?

**Comment by krokodilerian** [comment]
I think the "choice empty" comes from the disabled checkbox at "common fixes", you can't select that.

**Comment by yoe** [comment]
Please always file one issue per problem encountered, otherwise it becomes too hard to track what's been fixed and what hasn't.

This issue is about the wrong numbers; filing a new one about the confusion related to disabled form elements (which I'll explain there)

**Comment by yoe** [comment]
The new issue is #14

**Comment by yoe** [comment]
This was fixed by being more explicit about telling perl that some things are numbers
