### ISSUE TITLE
documentation does not exist yet

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#16]
https://review.video.fosdem.org/review/eb767ddd36c447db53456c65f439a4913ed48d77c19fa37984890fbf3342fb76

In the "cut pending" state, the link to the documentation does not work. It refers to the page itself.

**Comment by yoe** [comment]
Right, that's because the documentation does not exist yet and hence we can't link to it :-)

**Comment by yoe** [comment]
This is related to #14. Basically, documentation needs to be written.

**Comment by yoe** [comment]
I've made a start on this (/docs in the repository) which should be somewhat useful, but it's probably good to improve upon that.

**Comment by yoe** [comment]
This issue was about a dead link to documentation. That bit of it has been fixed. We may need to add more documentation, but don't need three issues to exist for that, so closing this one
