### ISSUE TITLE
use pseudocutting where possible

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#19]
Pseudocutting is available and reliable. You may want to actively use this feature in future versions of sreview (not for FOSDEM 2017).

Would speed up things quite a bit and provide almost instant feedback...

**Comment by yoe** [comment]
except it doesn't, since pseudocutting requires that we wait until the end of the day before we can do review. Need to have FOSDEM/video#80 fixed before this can happen -- and then we probably don't need pseudocutting anymore.

TBD.

**Comment by yoe** [comment]
This is not going to happen.
