### ISSUE TITLE
How to install dependencies?

### ISSUE THREAD

**Issue by kasbah** [yoe/sreview#35]
So far I figured out I need to do `cpan Mojolicious::Lite` and `cpan DBI` but now I am getting:

```
$ ./sreview daemon
Can't locate experimental.pm in @INC (you may need to install the experimental module) (@INC contains: /home/kaspar/perl5/lib/perl5/5.18.2/x86_64-linux-gnu-thread-multi /home/kaspar/perl5/lib/perl5/5.18.2 /home/kaspar/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/kaspar/perl5/lib/perl5 /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /home/kaspar/perl5/lib/perl5/5.18.1 /usr/local/lib/site_perl .) at ./sreview line 28.
BEGIN failed--compilation aborted at ./sreview line 28.
```

and there doesn't seem to be an `experimental` module.

**Comment by yoe** [comment]
Did you manage to get this to work with the commit I added?

**Comment by kasbah** [comment]
Yes, I think so. I installed all the dependencies: 

```
cpan Mojolicious::Lite DBI YAML DBD::Pg
```

I have just stopped short of setting up the database because I can't fully remember how to SQL.

**Comment by yoe** [comment]
psql -f db.sql <database name>

Let me regenerate that first though, a few changes have happened recently that I need to account for still
