### ISSUE TITLE
credits for reviewer

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#4]
Credits to the reviewer in the title slide. Should encourage participation and quality.

Whatever can be written quickly should be sufficient. No need for locking one video to one contributor etcetera...

**Comment by yoe** [comment]
I'm not convinced this will be a net plus. TBD.

**Comment by yoe** [comment]
If someone comes up with a patch that is not too ugly, this may happen. I'm not going to write it myself though, so closing this but for now.
