### ISSUE TITLE
pointy clicky start and stop selection

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#5]
See https://jsfiddle.net/6anrvo3s/ . If in trouble, krokodilerian's friend who cooked this up in 3 minutes might be able to help...

Worst case quick and dirty solution is to just do something with inputting values into a form and actually seeing the live output before actually sending it off.

**Comment by yoe** [comment]
I agree that this is a good idea, but my javascript skills are minimal at best. If someone with more of those would care to look at it, that would be appreciated.

The relevant code is found at https://github.com/yoe/sreview/blob/master/web/sreview#L45 (bit which updates a talk after form submission) and https://github.com/yoe/sreview/blob/master/web/templates/talk.html.ep (form template that shows the video). Ideally, the javascript would just update the other form fields.

The form fields are called "correction_length_adj" (should the amount of extra seconds added (positive) or seconds to be subtracted (negative) to or from the length of the video) and "correction_offset_start" (should contain the number of seconds to be added to (positive) or subtracted (negative) from the start point of the video).

The idea will be that I'll add smaller "5 minutes after your talk slot" and "5 minutes before your talk slot" videos before and after the "main" video as well (which will not be set to autoplay). Each video should have a button in the style of "make this the start of the recording" and/or "make this the end of the recording".

If it would be easier to change the type of form fields (e.g., make them say "absolute start" or some such), we can consider that (but it would be slightly more difficult for the backend).

**Comment by markvdb** [comment]
Potentially relevant:

http://www.annodex.net/~silvia/itext/mediafrag.html#t=40

**Comment by markvdb** [comment]
On the javascript side, stuff like https://github.com/tjenkinson/clappr-markers-plugin or https://github.com/spchuang/videojs-markers could be used to set the markers.

**Comment by yoe** [comment]
Webforms have been updated. Still need to do the javascript side.

Current high priority is to add a `cut_talk` script that works with the FOSDEM infrastructure, and test a complete runthrough of everything. After that, if nobody pops up to help out with this, I can look into this further (but it won't be as good then)

**Comment by yoe** [comment]
What the javascript would need to do:

- Add two buttons under each of the three &lt;video&gt; elements. (this could be done in static HTML if it's easier): one that says "take this as the start point of the video", one that says "take this as the end point of the video" (or something equivalent that uses less words)
- When clicked,
    - search the DOM for the radio button with the `id="standard` attribute, and ensure that it is active
    - Perform the right calculation(s) from the below list:
        - pre video, start button:
                LAn = LAl + (Lv1 - Tv1)
                SAn = SAl - (Lv1 - Tv1)
        - pre video, end button:
                LAn = LAl - Lv2 - (Lv1 - Tv1)
        - main video, start button:
                LAn = LAl - Tv2
                SAn = SAl + Tv2
        - main video, end button:
                LAn = LAl - (Lv2 - Tv2)
        - post video, start button:
                LAn = LAl - Lv2 - Tv3
                SAn = SAl + Lv2 + Tv3
        - post video, end button:
                LAn = LAl + Tv3
        where LAn is the new value for the `<input type="text" name="correction_length_adj">` element and LAl is the value of that element at page load time; SAn is the new value for the `<input type="text" name="correction_offset_start">` element and SAl is the value of that element at page load time; LvX is the length in seconds of video X; TvX is the current time of the playback of video X (which may be paused); video 1 is the pre video, video 2 is the main video, and video 3 is the post video.
    - Update the two &lt;input&gt; fields with their new values

If it helps, obviously we can generate some javascript so that the LAl, SAl, and LvX values don't need to be captured at page load time but they're known directly as variables.

**Comment by yoe** [comment]
Also, it might be nice if the javascript could produce an error if Lv2 + SAn - LAn < 0. That would mean the end point is before the start point, which is a nonsensical situation

**Comment by yoe** [comment]
cut_talks now actually also generates pre and post videos

**Comment by yoe** [comment]
There were still some bugs in commit 9980db7, but the javascript seems to work now.
