### ISSUE TITLE
packages not found in debian experimental

### ISSUE THREAD

**Issue by JurgenG** [yoe/sreview#56]
When clicking on the links presented in the installation instructions...

Install the packages sreview-detect, sreview-master, sreview-encoder, and sreview-web on a single machine.

... an error gets thrown:

Package not available in this suite.

**Comment by yoe** [comment]
Ah, yes -- the packages have since moved to Debian unstable. There's some bugs in there though, which I only uncovered when preparing for FOSDEM; you might want to build from git currently (I plan to upload to Debian soon, but have other priorities right now...)

**Comment by yoe** [comment]
Upload of 0.3.0 to Debian unstable has now happened; I'll update the instructions soon.

**Comment by yoe** [comment]
This was fixed in 4c6358372c0502ae4dc2d04789fae080b0669dff
