### ISSUE TITLE
Issues with /released metadata

### ISSUE THREAD

**Issue by stefanor** [yoe/SReview#59]
The metadata is attempting to be compatible with debconf-video's [archive-meta](https://salsa.debian.org/debconf-video-team/archive-meta/blob/master/schema.yml), but there are some issues:

Conference:
1. Would be nice to have `video_base`
1. And `schedule`

Formats:
1. `video_formats` is a list of dicts, it should be a dict.
1. The bitrate is an unqualified integer. It should probably be `1024k` or `1m`, not `1024`.
1. Missing `container`

Talks:
1. Speakers is a single string, not a string per speaker.
1. Descriptions are `null`. I'd prefer to omit it, if you don't know it.
1. `eventid` isn't a defined key.

**Comment by stefanor** [comment]
Here's what I'm doing to fix & improve the data: https://salsa.debian.org/debconf-video-team/archive-meta/blob/master/tools/sreview.py

**Comment by yoe** [comment]
also, we apparently only list the file as it is produced under the first profile, rather than under all profiles

**Comment by stefanor** [comment]
Also, the "default" format is the "lq" format, and the "webm" format is what we'd call the default.
