### ISSUE TITLE
Selecting the "start / end of the talk is not this video" options should fade any visible video notifications

### ISSUE THREAD

**Issue by belenbarrospena** [yoe/SReview#63]
Steps to reproduce:

1. Load the video review page
2. Select "The video has problems. "
3. In the "Start time" section, select "The video starts too late (the beginning of the talk is missing)"
4. Move the video scrubber forward and click the "Set new start time" button. The new video times notification will fade in. 
5. Select the checkbox for "The start of the talk is not in this video" option.

Outcome: the new video times notification is still visible. It only disppears if I click the "Set new start time" button again. This also happens with "The end of the talk is not in this video" option.

Expected outcome: the video notification should fade out, and the "Set new start time" button should become disabled. The button should only be re-enabled if I deselect the checkbox (sorry: I forgot to specify this interaction when I designed the screen).

The "is not in this video" options, when selected, should override any new video times. Basically, they are incompatible: you either set a new video time, or you select the "is not in this video" option.

**Comment by yoe** [comment]
They do override, but yeah, didn't think about the fact that, indeed, it might be a good idea to also hide the other notification.

**Comment by yoe** [comment]
Fixed this.

Side note: if someone clicks the "start time is missing" checkbox after selecting another time through the slider, that does *not* clear the set time, unless and until they click the "Set new end time"/"Set new start time" button.

Should I change this?
