### ISSUE TITLE
Documentation test with devroom manager

### ISSUE THREAD

**Issue by markvdb** [yoe/sreview#7]
For sreview to be usable for reviewers, we need a tutorial. Video or screenshots, whatever... I will gladly make that once sreview is sufficiently stable.

**Comment by markvdb** [comment]
Agk suggested http://html5test.com/ as a hard requirement.

**Comment by yoe** [comment]
It is unlikely that the review form will change anymore. If you're still willing to work on this, now would be the best time for that; be my guest.

**Comment by markvdb** [comment]
Wouter, I need to be able to run through the full process before I can attempt to create a manual. Some basic things seem to be missing/not working properly in the currently installed version. It's probably just small bits here and there, but it's not really possible to explain well to people how to use this without having used it yourself.

Please be quick to fix the issues if you expect me to try and help with a manual.

**Comment by yoe** [comment]
Is this still required, now that there's a minimal amount of documentation?

**Comment by markvdb** [comment]
It would be good to test the current setup with a devroom manager. Johan Vandewauw is an ideal candidate, as he's a devroom manager and involved with video.

**Comment by yoe** [comment]
@johanvdw, if you post your email address (on IRC would work), I can make it so you get to see the 'preview ready' emails. We can then do this.

Does that work for you?

**Comment by yoe** [comment]
@johanvdw: ping?

**Comment by yoe** [comment]
this never happened, and is now too late anyway
