### ISSUE TITLE
The video review page is not showing the link to the published video

### ISSUE THREAD

**Issue by belenbarrospena** [yoe/SReview#70]
If you click on the link to review a video, and that video has already been published, the link to the video is missing. See attached screenshot:

![video_published](https://user-images.githubusercontent.com/684113/52369297-4713c280-2a48-11e9-97e4-de3fe44f45b7.png)

Once a video is published, that page should show a link to the session page, as in https://belenbarrospena.github.io/sreview_design/published.html

**Comment by yoe** [comment]
This was a fairly simple fix in the end -- a configuration item was missing from the SReview production configuration, which meant that the URL could not be constructed, and the code then just doesn't return a URL. Once I fixed that, everything worked \o/

If you try the same URL now, you'll see the correct link posted.
